//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:07 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.annul;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnulmentCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AnnulmentCodeType">
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType32">
 *     &lt;enumeration value="ERRATIC_DATA"/>
 *     &lt;enumeration value="ERRATIC_INVOICE_NUMBER"/>
 *     &lt;enumeration value="ERRATIC_INVOICE_ISSUE_DATE"/>
 *     &lt;enumeration value="ERRATIC_ELECTRONIC_HASH_VALUE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AnnulmentCodeType")
@XmlEnum
public enum AnnulmentCodeType {


    /**
     * Technical annulment due to erratic data content
     * 
     */
    ERRATIC_DATA,

    /**
     * Technical annulment due to erratic invoice number
     * 
     */
    ERRATIC_INVOICE_NUMBER,

    /**
     * Technical annulment due to erratic invoice issue date
     * 
     */
    ERRATIC_INVOICE_ISSUE_DATE,

    /**
     * Technical annulment due to erratic electronic invoice hash value
     * 
     */
    ERRATIC_ELECTRONIC_HASH_VALUE;

    public String value() {
        return name();
    }

    public static AnnulmentCodeType fromValue(String v) {
        return valueOf(v);
    }

}
