//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:41 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.metrics;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MetricTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MetricTypeType">
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType15">
 *     &lt;enumeration value="COUNTER"/>
 *     &lt;enumeration value="GAUGE"/>
 *     &lt;enumeration value="HISTOGRAM"/>
 *     &lt;enumeration value="SUMMARY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MetricTypeType")
@XmlEnum
public enum MetricTypeType {


    /**
     * Incremental type metric
     * 
     */
    COUNTER,

    /**
     * Snapshot type metric
     * 
     */
    GAUGE,

    /**
     * Quantile type, dispersion sampler metric
     * 
     */
    HISTOGRAM,

    /**
     * Sum value type metric
     * 
     */
    SUMMARY;

    public String value() {
        return name();
    }

    public static MetricTypeType fromValue(String v) {
        return valueOf(v);
    }

}
