//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:41 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.metrics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Metric data type
 * 
 * <p>Java class for MetricType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MetricType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metricDefinition" type="{http://schemas.nav.gov.hu/OSA/3.0/metrics}MetricDefinitionType"/>
 *         &lt;element name="metricValues" type="{http://schemas.nav.gov.hu/OSA/3.0/metrics}MetricValueType" maxOccurs="60" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetricType", propOrder = {
    "metricDefinition",
    "metricValues"
})
public class MetricType {

    @XmlElement(required = true)
    protected MetricDefinitionType metricDefinition;
    protected List<MetricValueType> metricValues;

    /**
     * Gets the value of the metricDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link MetricDefinitionType }
     *     
     */
    public MetricDefinitionType getMetricDefinition() {
        return metricDefinition;
    }

    /**
     * Sets the value of the metricDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetricDefinitionType }
     *     
     */
    public void setMetricDefinition(MetricDefinitionType value) {
        this.metricDefinition = value;
    }

    /**
     * Gets the value of the metricValues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metricValues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetricValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetricValueType }
     * 
     * 
     */
    public List<MetricValueType> getMetricValues() {
        if (metricValues == null) {
            metricValues = new ArrayList<MetricValueType>();
        }
        return this.metricValues;
    }

}
