//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:41 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.metrics;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.gov.nav.schemas.osa._3_0.metrics package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.gov.nav.schemas.osa._3_0.metrics
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryServiceMetricsListResponse }
     * 
     */
    public QueryServiceMetricsListResponse createQueryServiceMetricsListResponse() {
        return new QueryServiceMetricsListResponse();
    }

    /**
     * Create an instance of {@link QueryServiceMetricsListResponseType }
     * 
     */
    public QueryServiceMetricsListResponseType createQueryServiceMetricsListResponseType() {
        return new QueryServiceMetricsListResponseType();
    }

    /**
     * Create an instance of {@link MetricDefinitionType }
     * 
     */
    public MetricDefinitionType createMetricDefinitionType() {
        return new MetricDefinitionType();
    }

    /**
     * Create an instance of {@link QueryServiceMetricsResponse }
     * 
     */
    public QueryServiceMetricsResponse createQueryServiceMetricsResponse() {
        return new QueryServiceMetricsResponse();
    }

    /**
     * Create an instance of {@link QueryServiceMetricsResponseType }
     * 
     */
    public QueryServiceMetricsResponseType createQueryServiceMetricsResponseType() {
        return new QueryServiceMetricsResponseType();
    }

    /**
     * Create an instance of {@link MetricType }
     * 
     */
    public MetricType createMetricType() {
        return new MetricType();
    }

    /**
     * Create an instance of {@link MetricDescriptionType }
     * 
     */
    public MetricDescriptionType createMetricDescriptionType() {
        return new MetricDescriptionType();
    }

    /**
     * Create an instance of {@link MetricValueType }
     * 
     */
    public MetricValueType createMetricValueType() {
        return new MetricValueType();
    }

}
