//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:41 PM CET 
//


package hu.gov.nav.schemas.ntca._1_0.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Denoting type of cryptographic method
 * 
 * <p>Java class for CryptoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CryptoType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://schemas.nav.gov.hu/NTCA/1.0/common>SimpleText512NotBlankType">
 *       &lt;attribute name="cryptoType" use="required" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText50NotBlankType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CryptoType", propOrder = {
    "value"
})
public class CryptoType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "cryptoType", required = true)
    protected String cryptoType;

    /**
     * String of maximum 512 characters
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the cryptoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCryptoType() {
        return cryptoType;
    }

    /**
     * Sets the value of the cryptoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCryptoType(String value) {
        this.cryptoType = value;
    }

}
