//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:41 PM CET 
//


package hu.gov.nav.schemas.ntca._1_0.common;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.gov.nav.schemas.ntca._1_0.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.gov.nav.schemas.ntca._1_0.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BasicResultType }
     * 
     */
    public BasicResultType createBasicResultType() {
        return new BasicResultType();
    }

    /**
     * Create an instance of {@link GeneralExceptionResponse }
     * 
     */
    public GeneralExceptionResponse createGeneralExceptionResponse() {
        return new GeneralExceptionResponse();
    }

    /**
     * Create an instance of {@link NotificationsType }
     * 
     */
    public NotificationsType createNotificationsType() {
        return new NotificationsType();
    }

    /**
     * Create an instance of {@link GeneralErrorHeaderResponse }
     * 
     */
    public GeneralErrorHeaderResponse createGeneralErrorHeaderResponse() {
        return new GeneralErrorHeaderResponse();
    }

    /**
     * Create an instance of {@link GeneralErrorHeaderResponseType }
     * 
     */
    public GeneralErrorHeaderResponseType createGeneralErrorHeaderResponseType() {
        return new GeneralErrorHeaderResponseType();
    }

    /**
     * Create an instance of {@link BasicResponseType }
     * 
     */
    public BasicResponseType createBasicResponseType() {
        return new BasicResponseType();
    }

    /**
     * Create an instance of {@link BasicHeaderType }
     * 
     */
    public BasicHeaderType createBasicHeaderType() {
        return new BasicHeaderType();
    }

    /**
     * Create an instance of {@link CryptoType }
     * 
     */
    public CryptoType createCryptoType() {
        return new CryptoType();
    }

    /**
     * Create an instance of {@link UserHeaderType }
     * 
     */
    public UserHeaderType createUserHeaderType() {
        return new UserHeaderType();
    }

    /**
     * Create an instance of {@link TechnicalValidationResultType }
     * 
     */
    public TechnicalValidationResultType createTechnicalValidationResultType() {
        return new TechnicalValidationResultType();
    }

    /**
     * Create an instance of {@link NotificationType }
     * 
     */
    public NotificationType createNotificationType() {
        return new NotificationType();
    }

    /**
     * Create an instance of {@link BasicRequestType }
     * 
     */
    public BasicRequestType createBasicRequestType() {
        return new BasicRequestType();
    }

}
