//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnulmentVerificationStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AnnulmentVerificationStatusType">
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType32">
 *     &lt;enumeration value="NOT_VERIFIABLE"/>
 *     &lt;enumeration value="VERIFICATION_PENDING"/>
 *     &lt;enumeration value="VERIFICATION_DONE"/>
 *     &lt;enumeration value="VERIFICATION_REJECTED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AnnulmentVerificationStatusType")
@XmlEnum
public enum AnnulmentVerificationStatusType {


    /**
     * The technical annulment is not verifiable due to client error
     * 
     */
    NOT_VERIFIABLE,

    /**
     * The technical annulment is awaiting verification
     * 
     */
    VERIFICATION_PENDING,

    /**
     * The technical annulment has been verified
     * 
     */
    VERIFICATION_DONE,

    /**
     * The technical annulment has been rejected
     * 
     */
    VERIFICATION_REJECTED;

    public String value() {
        return name();
    }

    public static AnnulmentVerificationStatusType fromValue(String v) {
        return valueOf(v);
    }

}
