//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Status data of technical annulment
 * 
 * <p>Java class for AnnulmentDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnulmentDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="annulmentVerificationStatus" type="{http://schemas.nav.gov.hu/OSA/3.0/api}AnnulmentVerificationStatusType"/>
 *         &lt;element name="annulmentDecisionDate" type="{http://schemas.nav.gov.hu/OSA/3.0/base}InvoiceTimestampType" minOccurs="0"/>
 *         &lt;element name="annulmentDecisionUser" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}LoginType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnulmentDataType", propOrder = {
    "annulmentVerificationStatus",
    "annulmentDecisionDate",
    "annulmentDecisionUser"
})
public class AnnulmentDataType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected AnnulmentVerificationStatusType annulmentVerificationStatus;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar annulmentDecisionDate;
    protected String annulmentDecisionUser;

    /**
     * Gets the value of the annulmentVerificationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link AnnulmentVerificationStatusType }
     *     
     */
    public AnnulmentVerificationStatusType getAnnulmentVerificationStatus() {
        return annulmentVerificationStatus;
    }

    /**
     * Sets the value of the annulmentVerificationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnulmentVerificationStatusType }
     *     
     */
    public void setAnnulmentVerificationStatus(AnnulmentVerificationStatusType value) {
        this.annulmentVerificationStatus = value;
    }

    /**
     * Gets the value of the annulmentDecisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAnnulmentDecisionDate() {
        return annulmentDecisionDate;
    }

    /**
     * Sets the value of the annulmentDecisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAnnulmentDecisionDate(XMLGregorianCalendar value) {
        this.annulmentDecisionDate = value;
    }

    /**
     * Gets the value of the annulmentDecisionUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnulmentDecisionUser() {
        return annulmentDecisionUser;
    }

    /**
     * Sets the value of the annulmentDecisionUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnulmentDecisionUser(String value) {
        this.annulmentDecisionUser = value;
    }

}
