//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import hu.gov.nav.schemas.ntca._1_0.common.BasicRequestType;


/**
 * Online Invoice specific basic request data
 * 
 * <p>Java class for BasicOnlineInvoiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicOnlineInvoiceRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.nav.gov.hu/NTCA/1.0/common}BasicRequestType">
 *       &lt;sequence>
 *         &lt;element name="software" type="{http://schemas.nav.gov.hu/OSA/3.0/api}SoftwareType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicOnlineInvoiceRequestType", propOrder = {
    "software"
})
@XmlSeeAlso({
    ManageAnnulmentRequestType.class,
    QueryInvoiceChainDigestRequestType.class,
    QueryTaxpayerRequestType.class,
    ManageInvoiceRequestType.class,
    QueryTransactionStatusRequestType.class,
    QueryInvoiceDigestRequestType.class,
    TokenExchangeRequest.class,
    QueryTransactionListRequestType.class,
    QueryInvoiceDataRequestType.class
})
public class BasicOnlineInvoiceRequestType
    extends BasicRequestType
{

    @XmlElement(required = true)
    protected SoftwareType software;

    /**
     * Gets the value of the software property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareType }
     *     
     */
    public SoftwareType getSoftware() {
        return software;
    }

    /**
     * Sets the value of the software property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareType }
     *     
     */
    public void setSoftware(SoftwareType value) {
        this.software = value;
    }

}
