//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncorporationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IncorporationType">
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType15">
 *     &lt;enumeration value="ORGANIZATION"/>
 *     &lt;enumeration value="SELF_EMPLOYED"/>
 *     &lt;enumeration value="TAXABLE_PERSON"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IncorporationType")
@XmlEnum
public enum IncorporationType {


    /**
     * Economical company
     * 
     */
    ORGANIZATION,

    /**
     * Self employed private entrepreneur
     * 
     */
    SELF_EMPLOYED,

    /**
     * Private person with tax number
     * 
     */
    TAXABLE_PERSON;

    public String value() {
        return name();
    }

    public static IncorporationType fromValue(String v) {
        return valueOf(v);
    }

}
