//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Invoice query parameters
 * 
 * <p>Java class for InvoiceQueryParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceQueryParamsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mandatoryQueryParams" type="{http://schemas.nav.gov.hu/OSA/3.0/api}MandatoryQueryParamsType"/>
 *         &lt;element name="additionalQueryParams" type="{http://schemas.nav.gov.hu/OSA/3.0/api}AdditionalQueryParamsType" minOccurs="0"/>
 *         &lt;element name="relationalQueryParams" type="{http://schemas.nav.gov.hu/OSA/3.0/api}RelationalQueryParamsType" minOccurs="0"/>
 *         &lt;element name="transactionQueryParams" type="{http://schemas.nav.gov.hu/OSA/3.0/api}TransactionQueryParamsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceQueryParamsType", propOrder = {
    "mandatoryQueryParams",
    "additionalQueryParams",
    "relationalQueryParams",
    "transactionQueryParams"
})
public class InvoiceQueryParamsType {

    @XmlElement(required = true)
    protected MandatoryQueryParamsType mandatoryQueryParams;
    protected AdditionalQueryParamsType additionalQueryParams;
    protected RelationalQueryParamsType relationalQueryParams;
    protected TransactionQueryParamsType transactionQueryParams;

    /**
     * Gets the value of the mandatoryQueryParams property.
     * 
     * @return
     *     possible object is
     *     {@link MandatoryQueryParamsType }
     *     
     */
    public MandatoryQueryParamsType getMandatoryQueryParams() {
        return mandatoryQueryParams;
    }

    /**
     * Sets the value of the mandatoryQueryParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandatoryQueryParamsType }
     *     
     */
    public void setMandatoryQueryParams(MandatoryQueryParamsType value) {
        this.mandatoryQueryParams = value;
    }

    /**
     * Gets the value of the additionalQueryParams property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalQueryParamsType }
     *     
     */
    public AdditionalQueryParamsType getAdditionalQueryParams() {
        return additionalQueryParams;
    }

    /**
     * Sets the value of the additionalQueryParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalQueryParamsType }
     *     
     */
    public void setAdditionalQueryParams(AdditionalQueryParamsType value) {
        this.additionalQueryParams = value;
    }

    /**
     * Gets the value of the relationalQueryParams property.
     * 
     * @return
     *     possible object is
     *     {@link RelationalQueryParamsType }
     *     
     */
    public RelationalQueryParamsType getRelationalQueryParams() {
        return relationalQueryParams;
    }

    /**
     * Sets the value of the relationalQueryParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationalQueryParamsType }
     *     
     */
    public void setRelationalQueryParams(RelationalQueryParamsType value) {
        this.relationalQueryParams = value;
    }

    /**
     * Gets the value of the transactionQueryParams property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionQueryParamsType }
     *     
     */
    public TransactionQueryParamsType getTransactionQueryParams() {
        return transactionQueryParams;
    }

    /**
     * Sets the value of the transactionQueryParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionQueryParamsType }
     *     
     */
    public void setTransactionQueryParams(TransactionQueryParamsType value) {
        this.transactionQueryParams = value;
    }

}
