//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Mandatory params of the invoice query
 * 
 * <p>Java class for MandatoryQueryParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MandatoryQueryParamsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="invoiceIssueDate" type="{http://schemas.nav.gov.hu/OSA/3.0/api}DateIntervalParamType"/>
 *         &lt;element name="insDate" type="{http://schemas.nav.gov.hu/OSA/3.0/api}DateTimeIntervalParamType"/>
 *         &lt;element name="originalInvoiceNumber" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText50NotBlankType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MandatoryQueryParamsType", propOrder = {
    "invoiceIssueDate",
    "insDate",
    "originalInvoiceNumber"
})
public class MandatoryQueryParamsType {

    protected DateIntervalParamType invoiceIssueDate;
    protected DateTimeIntervalParamType insDate;
    protected String originalInvoiceNumber;

    /**
     * Gets the value of the invoiceIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateIntervalParamType }
     *     
     */
    public DateIntervalParamType getInvoiceIssueDate() {
        return invoiceIssueDate;
    }

    /**
     * Sets the value of the invoiceIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateIntervalParamType }
     *     
     */
    public void setInvoiceIssueDate(DateIntervalParamType value) {
        this.invoiceIssueDate = value;
    }

    /**
     * Gets the value of the insDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeIntervalParamType }
     *     
     */
    public DateTimeIntervalParamType getInsDate() {
        return insDate;
    }

    /**
     * Sets the value of the insDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeIntervalParamType }
     *     
     */
    public void setInsDate(DateTimeIntervalParamType value) {
        this.insDate = value;
    }

    /**
     * Gets the value of the originalInvoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalInvoiceNumber() {
        return originalInvoiceNumber;
    }

    /**
     * Sets the value of the originalInvoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalInvoiceNumber(String value) {
        this.originalInvoiceNumber = value;
    }

}
