//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * New invoice lines created by the modification document
 * 
 * <p>Java class for NewCreatedLinesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewCreatedLinesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lineNumberIntervalStart" type="{http://schemas.nav.gov.hu/OSA/3.0/base}LineNumberType"/>
 *         &lt;element name="lineNumberIntervalEnd" type="{http://schemas.nav.gov.hu/OSA/3.0/base}LineNumberType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewCreatedLinesType", propOrder = {
    "lineNumberIntervalStart",
    "lineNumberIntervalEnd"
})
public class NewCreatedLinesType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger lineNumberIntervalStart;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger lineNumberIntervalEnd;

    /**
     * Gets the value of the lineNumberIntervalStart property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineNumberIntervalStart() {
        return lineNumberIntervalStart;
    }

    /**
     * Sets the value of the lineNumberIntervalStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineNumberIntervalStart(BigInteger value) {
        this.lineNumberIntervalStart = value;
    }

    /**
     * Gets the value of the lineNumberIntervalEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineNumberIntervalEnd() {
        return lineNumberIntervalEnd;
    }

    /**
     * Sets the value of the lineNumberIntervalEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineNumberIntervalEnd(BigInteger value) {
        this.lineNumberIntervalEnd = value;
    }

}
