//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Response type of the POST /queryTransactionStatus REST operation
 * 
 * <p>Java class for QueryTransactionStatusResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryTransactionStatusResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/3.0/api}BasicOnlineInvoiceResponseType">
 *       &lt;sequence>
 *         &lt;element name="processingResults" type="{http://schemas.nav.gov.hu/OSA/3.0/api}ProcessingResultListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryTransactionStatusResponseType", propOrder = {
    "processingResults"
})
@XmlSeeAlso({
    QueryTransactionStatusResponse.class
})
public class QueryTransactionStatusResponseType
    extends BasicOnlineInvoiceResponseType
{

    protected ProcessingResultListType processingResults;

    /**
     * Gets the value of the processingResults property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingResultListType }
     *     
     */
    public ProcessingResultListType getProcessingResults() {
        return processingResults;
    }

    /**
     * Sets the value of the processingResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingResultListType }
     *     
     */
    public void setProcessingResults(ProcessingResultListType value) {
        this.processingResults = value;
    }

}
