//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Request type of the POST /queryInvoiceData REST operation
 * 
 * <p>Java class for QueryInvoiceDataRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryInvoiceDataRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/3.0/api}BasicOnlineInvoiceRequestType">
 *       &lt;sequence>
 *         &lt;element name="invoiceNumberQuery" type="{http://schemas.nav.gov.hu/OSA/3.0/api}InvoiceNumberQueryType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryInvoiceDataRequestType", propOrder = {
    "invoiceNumberQuery"
})
@XmlSeeAlso({
    QueryInvoiceCheckRequest.class,
    QueryInvoiceDataRequest.class
})
public class QueryInvoiceDataRequestType
    extends BasicOnlineInvoiceRequestType
{

    @XmlElement(required = true)
    protected InvoiceNumberQueryType invoiceNumberQuery;

    /**
     * Gets the value of the invoiceNumberQuery property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceNumberQueryType }
     *     
     */
    public InvoiceNumberQueryType getInvoiceNumberQuery() {
        return invoiceNumberQuery;
    }

    /**
     * Sets the value of the invoiceNumberQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceNumberQueryType }
     *     
     */
    public void setInvoiceNumberQuery(InvoiceNumberQueryType value) {
        this.invoiceNumberQuery = value;
    }

}
