//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Response type of the POST /queryInvoiceDigest REST operation
 * 
 * <p>Java class for QueryInvoiceDigestResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryInvoiceDigestResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/3.0/api}BasicOnlineInvoiceResponseType">
 *       &lt;sequence>
 *         &lt;element name="invoiceDigestResult" type="{http://schemas.nav.gov.hu/OSA/3.0/api}InvoiceDigestResultType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryInvoiceDigestResponseType", propOrder = {
    "invoiceDigestResult"
})
@XmlSeeAlso({
    QueryInvoiceDigestResponse.class
})
public class QueryInvoiceDigestResponseType
    extends BasicOnlineInvoiceResponseType
{

    @XmlElement(required = true)
    protected InvoiceDigestResultType invoiceDigestResult;

    /**
     * Gets the value of the invoiceDigestResult property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDigestResultType }
     *     
     */
    public InvoiceDigestResultType getInvoiceDigestResult() {
        return invoiceDigestResult;
    }

    /**
     * Sets the value of the invoiceDigestResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDigestResultType }
     *     
     */
    public void setInvoiceDigestResult(InvoiceDigestResultType value) {
        this.invoiceDigestResult = value;
    }

}
