//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Request type of the POST /queryTransactionList REST operation
 * 
 * <p>Java class for QueryTransactionListRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryTransactionListRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/3.0/api}BasicOnlineInvoiceRequestType">
 *       &lt;sequence>
 *         &lt;element name="page" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}RequestPageType"/>
 *         &lt;element name="insDate" type="{http://schemas.nav.gov.hu/OSA/3.0/api}DateTimeIntervalParamType"/>
 *         &lt;element name="requestStatus" type="{http://schemas.nav.gov.hu/OSA/3.0/api}RequestStatusType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryTransactionListRequestType", propOrder = {
    "page",
    "insDate",
    "requestStatus"
})
@XmlSeeAlso({
    QueryTransactionListRequest.class
})
public class QueryTransactionListRequestType
    extends BasicOnlineInvoiceRequestType
{

    protected int page;
    @XmlElement(required = true)
    protected DateTimeIntervalParamType insDate;
    @XmlSchemaType(name = "string")
    protected RequestStatusType requestStatus;

    /**
     * Gets the value of the page property.
     * 
     */
    public int getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     */
    public void setPage(int value) {
        this.page = value;
    }

    /**
     * Gets the value of the insDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeIntervalParamType }
     *     
     */
    public DateTimeIntervalParamType getInsDate() {
        return insDate;
    }

    /**
     * Sets the value of the insDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeIntervalParamType }
     *     
     */
    public void setInsDate(DateTimeIntervalParamType value) {
        this.insDate = value;
    }

    /**
     * Gets the value of the requestStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RequestStatusType }
     *     
     */
    public RequestStatusType getRequestStatus() {
        return requestStatus;
    }

    /**
     * Sets the value of the requestStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestStatusType }
     *     
     */
    public void setRequestStatus(RequestStatusType value) {
        this.requestStatus = value;
    }

}
