//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import hu.gov.nav.schemas.osa._3_0.base.DetailedAddressType;


/**
 * Taxpayer address item
 * 
 * <p>Java class for TaxpayerAddressItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxpayerAddressItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="taxpayerAddressType" type="{http://schemas.nav.gov.hu/OSA/3.0/api}TaxpayerAddressTypeType"/>
 *         &lt;element name="taxpayerAddress" type="{http://schemas.nav.gov.hu/OSA/3.0/base}DetailedAddressType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxpayerAddressItemType", propOrder = {
    "taxpayerAddressType",
    "taxpayerAddress"
})
public class TaxpayerAddressItemType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TaxpayerAddressTypeType taxpayerAddressType;
    @XmlElement(required = true)
    protected DetailedAddressType taxpayerAddress;

    /**
     * Gets the value of the taxpayerAddressType property.
     * 
     * @return
     *     possible object is
     *     {@link TaxpayerAddressTypeType }
     *     
     */
    public TaxpayerAddressTypeType getTaxpayerAddressType() {
        return taxpayerAddressType;
    }

    /**
     * Sets the value of the taxpayerAddressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxpayerAddressTypeType }
     *     
     */
    public void setTaxpayerAddressType(TaxpayerAddressTypeType value) {
        this.taxpayerAddressType = value;
    }

    /**
     * Gets the value of the taxpayerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link DetailedAddressType }
     *     
     */
    public DetailedAddressType getTaxpayerAddress() {
        return taxpayerAddress;
    }

    /**
     * Sets the value of the taxpayerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailedAddressType }
     *     
     */
    public void setTaxpayerAddress(DetailedAddressType value) {
        this.taxpayerAddress = value;
    }

}
