//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:16 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import hu.gov.nav.schemas.osa._3_0.base.TaxNumberType;


/**
 * Response data of the taxpayer query
 * 
 * <p>Java class for TaxpayerDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxpayerDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="taxpayerName" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText512NotBlankType"/>
 *         &lt;element name="taxpayerShortName" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText200NotBlankType" minOccurs="0"/>
 *         &lt;element name="taxNumberDetail" type="{http://schemas.nav.gov.hu/OSA/3.0/base}TaxNumberType"/>
 *         &lt;element name="incorporation" type="{http://schemas.nav.gov.hu/OSA/3.0/api}IncorporationType"/>
 *         &lt;element name="vatGroupMembership" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}TaxpayerIdType" minOccurs="0"/>
 *         &lt;element name="taxpayerAddressList" type="{http://schemas.nav.gov.hu/OSA/3.0/api}TaxpayerAddressListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxpayerDataType", propOrder = {
    "taxpayerName",
    "taxpayerShortName",
    "taxNumberDetail",
    "incorporation",
    "vatGroupMembership",
    "taxpayerAddressList"
})
public class TaxpayerDataType {

    @XmlElement(required = true)
    protected String taxpayerName;
    protected String taxpayerShortName;
    @XmlElement(required = true)
    protected TaxNumberType taxNumberDetail;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected IncorporationType incorporation;
    protected String vatGroupMembership;
    protected TaxpayerAddressListType taxpayerAddressList;

    /**
     * Gets the value of the taxpayerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxpayerName() {
        return taxpayerName;
    }

    /**
     * Sets the value of the taxpayerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxpayerName(String value) {
        this.taxpayerName = value;
    }

    /**
     * Gets the value of the taxpayerShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxpayerShortName() {
        return taxpayerShortName;
    }

    /**
     * Sets the value of the taxpayerShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxpayerShortName(String value) {
        this.taxpayerShortName = value;
    }

    /**
     * Gets the value of the taxNumberDetail property.
     * 
     * @return
     *     possible object is
     *     {@link TaxNumberType }
     *     
     */
    public TaxNumberType getTaxNumberDetail() {
        return taxNumberDetail;
    }

    /**
     * Sets the value of the taxNumberDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxNumberType }
     *     
     */
    public void setTaxNumberDetail(TaxNumberType value) {
        this.taxNumberDetail = value;
    }

    /**
     * Gets the value of the incorporation property.
     * 
     * @return
     *     possible object is
     *     {@link IncorporationType }
     *     
     */
    public IncorporationType getIncorporation() {
        return incorporation;
    }

    /**
     * Sets the value of the incorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncorporationType }
     *     
     */
    public void setIncorporation(IncorporationType value) {
        this.incorporation = value;
    }

    /**
     * Gets the value of the vatGroupMembership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatGroupMembership() {
        return vatGroupMembership;
    }

    /**
     * Sets the value of the vatGroupMembership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatGroupMembership(String value) {
        this.vatGroupMembership = value;
    }

    /**
     * Gets the value of the taxpayerAddressList property.
     * 
     * @return
     *     possible object is
     *     {@link TaxpayerAddressListType }
     *     
     */
    public TaxpayerAddressListType getTaxpayerAddressList() {
        return taxpayerAddressList;
    }

    /**
     * Sets the value of the taxpayerAddressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxpayerAddressListType }
     *     
     */
    public void setTaxpayerAddressList(TaxpayerAddressListType value) {
        this.taxpayerAddressList = value;
    }

}
