//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Advance related data
 * 
 * <p>Java class for AdvanceDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdvanceDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="advanceIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="advancePaymentData" type="{http://schemas.nav.gov.hu/OSA/3.0/data}AdvancePaymentDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdvanceDataType", propOrder = {
    "advanceIndicator",
    "advancePaymentData"
})
public class AdvanceDataType {

    protected boolean advanceIndicator;
    protected AdvancePaymentDataType advancePaymentData;

    /**
     * Gets the value of the advanceIndicator property.
     * 
     */
    public boolean isAdvanceIndicator() {
        return advanceIndicator;
    }

    /**
     * Sets the value of the advanceIndicator property.
     * 
     */
    public void setAdvanceIndicator(boolean value) {
        this.advanceIndicator = value;
    }

    /**
     * Gets the value of the advancePaymentData property.
     * 
     * @return
     *     possible object is
     *     {@link AdvancePaymentDataType }
     *     
     */
    public AdvancePaymentDataType getAdvancePaymentData() {
        return advancePaymentData;
    }

    /**
     * Sets the value of the advancePaymentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdvancePaymentDataType }
     *     
     */
    public void setAdvancePaymentData(AdvancePaymentDataType value) {
        this.advancePaymentData = value;
    }

}
