//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Advance payment related data
 * 
 * <p>Java class for AdvancePaymentDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdvancePaymentDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="advanceOriginalInvoice" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText50NotBlankType"/>
 *         &lt;element name="advancePaymentDate" type="{http://schemas.nav.gov.hu/OSA/3.0/base}InvoiceDateType"/>
 *         &lt;element name="advanceExchangeRate" type="{http://schemas.nav.gov.hu/OSA/3.0/data}ExchangeRateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdvancePaymentDataType", propOrder = {
    "advanceOriginalInvoice",
    "advancePaymentDate",
    "advanceExchangeRate"
})
public class AdvancePaymentDataType {

    @XmlElement(required = true)
    protected String advanceOriginalInvoice;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar advancePaymentDate;
    @XmlElement(required = true)
    protected BigDecimal advanceExchangeRate;

    /**
     * Gets the value of the advanceOriginalInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvanceOriginalInvoice() {
        return advanceOriginalInvoice;
    }

    /**
     * Sets the value of the advanceOriginalInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvanceOriginalInvoice(String value) {
        this.advanceOriginalInvoice = value;
    }

    /**
     * Gets the value of the advancePaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAdvancePaymentDate() {
        return advancePaymentDate;
    }

    /**
     * Sets the value of the advancePaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAdvancePaymentDate(XMLGregorianCalendar value) {
        this.advancePaymentDate = value;
    }

    /**
     * Gets the value of the advanceExchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdvanceExchangeRate() {
        return advanceExchangeRate;
    }

    /**
     * Sets the value of the advanceExchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdvanceExchangeRate(BigDecimal value) {
        this.advanceExchangeRate = value;
    }

}
