//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Field type including aggregate invoice special data
 * 
 * <p>Java class for AggregateInvoiceLineDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AggregateInvoiceLineDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lineExchangeRate" type="{http://schemas.nav.gov.hu/OSA/3.0/data}ExchangeRateType" minOccurs="0"/>
 *         &lt;element name="lineDeliveryDate" type="{http://schemas.nav.gov.hu/OSA/3.0/base}InvoiceDateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AggregateInvoiceLineDataType", propOrder = {
    "lineExchangeRate",
    "lineDeliveryDate"
})
public class AggregateInvoiceLineDataType {

    protected BigDecimal lineExchangeRate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lineDeliveryDate;

    /**
     * Gets the value of the lineExchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineExchangeRate() {
        return lineExchangeRate;
    }

    /**
     * Sets the value of the lineExchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineExchangeRate(BigDecimal value) {
        this.lineExchangeRate = value;
    }

    /**
     * Gets the value of the lineDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLineDeliveryDate() {
        return lineDeliveryDate;
    }

    /**
     * Sets the value of the lineDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLineDeliveryDate(XMLGregorianCalendar value) {
        this.lineDeliveryDate = value;
    }

}
