//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import hu.gov.nav.schemas.osa._3_0.base.TaxNumberType;


/**
 * Tax number or group identification number, under which the purchase of goods or services is done
 * 
 * <p>Java class for CustomerTaxNumberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerTaxNumberType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.nav.gov.hu/OSA/3.0/base}TaxNumberType">
 *       &lt;sequence>
 *         &lt;element name="groupMemberTaxNumber" type="{http://schemas.nav.gov.hu/OSA/3.0/base}TaxNumberType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerTaxNumberType", propOrder = {
    "groupMemberTaxNumber"
})
public class CustomerTaxNumberType
    extends TaxNumberType
{

    protected TaxNumberType groupMemberTaxNumber;

    /**
     * Gets the value of the groupMemberTaxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TaxNumberType }
     *     
     */
    public TaxNumberType getGroupMemberTaxNumber() {
        return groupMemberTaxNumber;
    }

    /**
     * Sets the value of the groupMemberTaxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxNumberType }
     *     
     */
    public void setGroupMemberTaxNumber(TaxNumberType value) {
        this.groupMemberTaxNumber = value;
    }

}
