//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Should the supplier, based on statement given by the purchaser, be exempted from paying product fee, then the product stream affected
 * 
 * <p>Java class for CustomerDeclarationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerDeclarationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productStream" type="{http://schemas.nav.gov.hu/OSA/3.0/data}ProductStreamType"/>
 *         &lt;element name="productFeeWeight" type="{http://schemas.nav.gov.hu/OSA/3.0/data}QuantityType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerDeclarationType", propOrder = {
    "productStream",
    "productFeeWeight"
})
public class CustomerDeclarationType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ProductStreamType productStream;
    protected BigDecimal productFeeWeight;

    /**
     * Gets the value of the productStream property.
     * 
     * @return
     *     possible object is
     *     {@link ProductStreamType }
     *     
     */
    public ProductStreamType getProductStream() {
        return productStream;
    }

    /**
     * Sets the value of the productStream property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductStreamType }
     *     
     */
    public void setProductStream(ProductStreamType value) {
        this.productStream = value;
    }

    /**
     * Gets the value of the productFeeWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProductFeeWeight() {
        return productFeeWeight;
    }

    /**
     * Sets the value of the productFeeWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductFeeWeight(BigDecimal value) {
        this.productFeeWeight = value;
    }

}
