//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Modification or cancellation reference data
 * 
 * <p>Java class for InvoiceReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originalInvoiceNumber" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText50NotBlankType"/>
 *         &lt;element name="modifyWithoutMaster" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="modificationIndex" type="{http://schemas.nav.gov.hu/OSA/3.0/base}InvoiceUnboundedIndexType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceReferenceType", propOrder = {
    "originalInvoiceNumber",
    "modifyWithoutMaster",
    "modificationIndex"
})
public class InvoiceReferenceType {

    @XmlElement(required = true)
    protected String originalInvoiceNumber;
    protected boolean modifyWithoutMaster;
    protected int modificationIndex;

    /**
     * Gets the value of the originalInvoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalInvoiceNumber() {
        return originalInvoiceNumber;
    }

    /**
     * Sets the value of the originalInvoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalInvoiceNumber(String value) {
        this.originalInvoiceNumber = value;
    }

    /**
     * Gets the value of the modifyWithoutMaster property.
     * 
     */
    public boolean isModifyWithoutMaster() {
        return modifyWithoutMaster;
    }

    /**
     * Sets the value of the modifyWithoutMaster property.
     * 
     */
    public void setModifyWithoutMaster(boolean value) {
        this.modifyWithoutMaster = value;
    }

    /**
     * Gets the value of the modificationIndex property.
     * 
     */
    public int getModificationIndex() {
        return modificationIndex;
    }

    /**
     * Sets the value of the modificationIndex property.
     * 
     */
    public void setModificationIndex(int value) {
        this.modificationIndex = value;
    }

}
