//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Line VAT data
 * 
 * <p>Java class for LineVatDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineVatDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lineVatAmount" type="{http://schemas.nav.gov.hu/OSA/3.0/base}MonetaryType"/>
 *         &lt;element name="lineVatAmountHUF" type="{http://schemas.nav.gov.hu/OSA/3.0/base}MonetaryType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineVatDataType", propOrder = {
    "lineVatAmount",
    "lineVatAmountHUF"
})
public class LineVatDataType {

    @XmlElement(required = true)
    protected BigDecimal lineVatAmount;
    @XmlElement(required = true)
    protected BigDecimal lineVatAmountHUF;

    /**
     * Gets the value of the lineVatAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineVatAmount() {
        return lineVatAmount;
    }

    /**
     * Sets the value of the lineVatAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineVatAmount(BigDecimal value) {
        this.lineVatAmount = value;
    }

    /**
     * Gets the value of the lineVatAmountHUF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineVatAmountHUF() {
        return lineVatAmountHUF;
    }

    /**
     * Sets the value of the lineVatAmountHUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineVatAmountHUF(BigDecimal value) {
        this.lineVatAmountHUF = value;
    }

}
