//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Marking the goal of modification of the line (in the case of data supply about changes/updates only)
 * 
 * <p>Java class for LineModificationReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineModificationReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lineNumberReference" type="{http://schemas.nav.gov.hu/OSA/3.0/base}LineNumberType"/>
 *         &lt;element name="lineOperation" type="{http://schemas.nav.gov.hu/OSA/3.0/data}LineOperationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineModificationReferenceType", propOrder = {
    "lineNumberReference",
    "lineOperation"
})
public class LineModificationReferenceType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger lineNumberReference;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LineOperationType lineOperation;

    /**
     * Gets the value of the lineNumberReference property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineNumberReference() {
        return lineNumberReference;
    }

    /**
     * Sets the value of the lineNumberReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineNumberReference(BigInteger value) {
        this.lineNumberReference = value;
    }

    /**
     * Gets the value of the lineOperation property.
     * 
     * @return
     *     possible object is
     *     {@link LineOperationType }
     *     
     */
    public LineOperationType getLineOperation() {
        return lineOperation;
    }

    /**
     * Sets the value of the lineOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineOperationType }
     *     
     */
    public void setLineOperation(LineOperationType value) {
        this.lineOperation = value;
    }

}
