//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.gov.nav.schemas.osa._3_0.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.gov.nav.schemas.osa._3_0.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceData }
     * 
     */
    public InvoiceData createInvoiceData() {
        return new InvoiceData();
    }

    /**
     * Create an instance of {@link InvoiceDataType }
     * 
     */
    public InvoiceDataType createInvoiceDataType() {
        return new InvoiceDataType();
    }

    /**
     * Create an instance of {@link InvoiceMainType }
     * 
     */
    public InvoiceMainType createInvoiceMainType() {
        return new InvoiceMainType();
    }

    /**
     * Create an instance of {@link DetailedReasonType }
     * 
     */
    public DetailedReasonType createDetailedReasonType() {
        return new DetailedReasonType();
    }

    /**
     * Create an instance of {@link SupplierInfoType }
     * 
     */
    public SupplierInfoType createSupplierInfoType() {
        return new SupplierInfoType();
    }

    /**
     * Create an instance of {@link VesselType }
     * 
     */
    public VesselType createVesselType() {
        return new VesselType();
    }

    /**
     * Create an instance of {@link ProjectNumbersType }
     * 
     */
    public ProjectNumbersType createProjectNumbersType() {
        return new ProjectNumbersType();
    }

    /**
     * Create an instance of {@link DeliveryNotesType }
     * 
     */
    public DeliveryNotesType createDeliveryNotesType() {
        return new DeliveryNotesType();
    }

    /**
     * Create an instance of {@link LineModificationReferenceType }
     * 
     */
    public LineModificationReferenceType createLineModificationReferenceType() {
        return new LineModificationReferenceType();
    }

    /**
     * Create an instance of {@link SummaryNormalType }
     * 
     */
    public SummaryNormalType createSummaryNormalType() {
        return new SummaryNormalType();
    }

    /**
     * Create an instance of {@link OrderNumbersType }
     * 
     */
    public OrderNumbersType createOrderNumbersType() {
        return new OrderNumbersType();
    }

    /**
     * Create an instance of {@link BatchInvoiceType }
     * 
     */
    public BatchInvoiceType createBatchInvoiceType() {
        return new BatchInvoiceType();
    }

    /**
     * Create an instance of {@link CustomerDeclarationType }
     * 
     */
    public CustomerDeclarationType createCustomerDeclarationType() {
        return new CustomerDeclarationType();
    }

    /**
     * Create an instance of {@link SummarySimplifiedType }
     * 
     */
    public SummarySimplifiedType createSummarySimplifiedType() {
        return new SummarySimplifiedType();
    }

    /**
     * Create an instance of {@link FiscalRepresentativeType }
     * 
     */
    public FiscalRepresentativeType createFiscalRepresentativeType() {
        return new FiscalRepresentativeType();
    }

    /**
     * Create an instance of {@link VatRateNetDataType }
     * 
     */
    public VatRateNetDataType createVatRateNetDataType() {
        return new VatRateNetDataType();
    }

    /**
     * Create an instance of {@link DiscountDataType }
     * 
     */
    public DiscountDataType createDiscountDataType() {
        return new DiscountDataType();
    }

    /**
     * Create an instance of {@link ProductCodeType }
     * 
     */
    public ProductCodeType createProductCodeType() {
        return new ProductCodeType();
    }

    /**
     * Create an instance of {@link AggregateInvoiceLineDataType }
     * 
     */
    public AggregateInvoiceLineDataType createAggregateInvoiceLineDataType() {
        return new AggregateInvoiceLineDataType();
    }

    /**
     * Create an instance of {@link ItemNumbersType }
     * 
     */
    public ItemNumbersType createItemNumbersType() {
        return new ItemNumbersType();
    }

    /**
     * Create an instance of {@link ProductFeeSummaryType }
     * 
     */
    public ProductFeeSummaryType createProductFeeSummaryType() {
        return new ProductFeeSummaryType();
    }

    /**
     * Create an instance of {@link VatRateGrossDataType }
     * 
     */
    public VatRateGrossDataType createVatRateGrossDataType() {
        return new VatRateGrossDataType();
    }

    /**
     * Create an instance of {@link ReferencesToOtherLinesType }
     * 
     */
    public ReferencesToOtherLinesType createReferencesToOtherLinesType() {
        return new ReferencesToOtherLinesType();
    }

    /**
     * Create an instance of {@link CustomerCompanyCodesType }
     * 
     */
    public CustomerCompanyCodesType createCustomerCompanyCodesType() {
        return new CustomerCompanyCodesType();
    }

    /**
     * Create an instance of {@link ProductCodesType }
     * 
     */
    public ProductCodesType createProductCodesType() {
        return new ProductCodesType();
    }

    /**
     * Create an instance of {@link ProductFeeClauseType }
     * 
     */
    public ProductFeeClauseType createProductFeeClauseType() {
        return new ProductFeeClauseType();
    }

    /**
     * Create an instance of {@link SupplierCompanyCodesType }
     * 
     */
    public SupplierCompanyCodesType createSupplierCompanyCodesType() {
        return new SupplierCompanyCodesType();
    }

    /**
     * Create an instance of {@link AdvanceDataType }
     * 
     */
    public AdvanceDataType createAdvanceDataType() {
        return new AdvanceDataType();
    }

    /**
     * Create an instance of {@link SummaryType }
     * 
     */
    public SummaryType createSummaryType() {
        return new SummaryType();
    }

    /**
     * Create an instance of {@link InvoiceHeadType }
     * 
     */
    public InvoiceHeadType createInvoiceHeadType() {
        return new InvoiceHeadType();
    }

    /**
     * Create an instance of {@link ShippingDatesType }
     * 
     */
    public ShippingDatesType createShippingDatesType() {
        return new ShippingDatesType();
    }

    /**
     * Create an instance of {@link ConventionalInvoiceInfoType }
     * 
     */
    public ConventionalInvoiceInfoType createConventionalInvoiceInfoType() {
        return new ConventionalInvoiceInfoType();
    }

    /**
     * Create an instance of {@link LineNetAmountDataType }
     * 
     */
    public LineNetAmountDataType createLineNetAmountDataType() {
        return new LineNetAmountDataType();
    }

    /**
     * Create an instance of {@link PaymentEvidenceDocumentDataType }
     * 
     */
    public PaymentEvidenceDocumentDataType createPaymentEvidenceDocumentDataType() {
        return new PaymentEvidenceDocumentDataType();
    }

    /**
     * Create an instance of {@link InvoiceDetailType }
     * 
     */
    public InvoiceDetailType createInvoiceDetailType() {
        return new InvoiceDetailType();
    }

    /**
     * Create an instance of {@link LineVatDataType }
     * 
     */
    public LineVatDataType createLineVatDataType() {
        return new LineVatDataType();
    }

    /**
     * Create an instance of {@link AircraftType }
     * 
     */
    public AircraftType createAircraftType() {
        return new AircraftType();
    }

    /**
     * Create an instance of {@link SummaryByVatRateType }
     * 
     */
    public SummaryByVatRateType createSummaryByVatRateType() {
        return new SummaryByVatRateType();
    }

    /**
     * Create an instance of {@link LineAmountsNormalType }
     * 
     */
    public LineAmountsNormalType createLineAmountsNormalType() {
        return new LineAmountsNormalType();
    }

    /**
     * Create an instance of {@link VatAmountMismatchType }
     * 
     */
    public VatAmountMismatchType createVatAmountMismatchType() {
        return new VatAmountMismatchType();
    }

    /**
     * Create an instance of {@link VatRateType }
     * 
     */
    public VatRateType createVatRateType() {
        return new VatRateType();
    }

    /**
     * Create an instance of {@link AdvancePaymentDataType }
     * 
     */
    public AdvancePaymentDataType createAdvancePaymentDataType() {
        return new AdvancePaymentDataType();
    }

    /**
     * Create an instance of {@link ContractNumbersType }
     * 
     */
    public ContractNumbersType createContractNumbersType() {
        return new ContractNumbersType();
    }

    /**
     * Create an instance of {@link GlnNumbersType }
     * 
     */
    public GlnNumbersType createGlnNumbersType() {
        return new GlnNumbersType();
    }

    /**
     * Create an instance of {@link ProductFeeTakeoverDataType }
     * 
     */
    public ProductFeeTakeoverDataType createProductFeeTakeoverDataType() {
        return new ProductFeeTakeoverDataType();
    }

    /**
     * Create an instance of {@link DieselOilPurchaseType }
     * 
     */
    public DieselOilPurchaseType createDieselOilPurchaseType() {
        return new DieselOilPurchaseType();
    }

    /**
     * Create an instance of {@link LinesType }
     * 
     */
    public LinesType createLinesType() {
        return new LinesType();
    }

    /**
     * Create an instance of {@link DealerCodesType }
     * 
     */
    public DealerCodesType createDealerCodesType() {
        return new DealerCodesType();
    }

    /**
     * Create an instance of {@link LineType }
     * 
     */
    public LineType createLineType() {
        return new LineType();
    }

    /**
     * Create an instance of {@link CustomerVatDataType }
     * 
     */
    public CustomerVatDataType createCustomerVatDataType() {
        return new CustomerVatDataType();
    }

    /**
     * Create an instance of {@link GeneralLedgerAccountNumbersType }
     * 
     */
    public GeneralLedgerAccountNumbersType createGeneralLedgerAccountNumbersType() {
        return new GeneralLedgerAccountNumbersType();
    }

    /**
     * Create an instance of {@link VatRateVatDataType }
     * 
     */
    public VatRateVatDataType createVatRateVatDataType() {
        return new VatRateVatDataType();
    }

    /**
     * Create an instance of {@link CustomerInfoType }
     * 
     */
    public CustomerInfoType createCustomerInfoType() {
        return new CustomerInfoType();
    }

    /**
     * Create an instance of {@link MaterialNumbersType }
     * 
     */
    public MaterialNumbersType createMaterialNumbersType() {
        return new MaterialNumbersType();
    }

    /**
     * Create an instance of {@link InvoiceReferenceType }
     * 
     */
    public InvoiceReferenceType createInvoiceReferenceType() {
        return new InvoiceReferenceType();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link SummaryGrossDataType }
     * 
     */
    public SummaryGrossDataType createSummaryGrossDataType() {
        return new SummaryGrossDataType();
    }

    /**
     * Create an instance of {@link ProductFeeDataType }
     * 
     */
    public ProductFeeDataType createProductFeeDataType() {
        return new ProductFeeDataType();
    }

    /**
     * Create an instance of {@link InvoiceType }
     * 
     */
    public InvoiceType createInvoiceType() {
        return new InvoiceType();
    }

    /**
     * Create an instance of {@link EkaerIdsType }
     * 
     */
    public EkaerIdsType createEkaerIdsType() {
        return new EkaerIdsType();
    }

    /**
     * Create an instance of {@link NewTransportMeanType }
     * 
     */
    public NewTransportMeanType createNewTransportMeanType() {
        return new NewTransportMeanType();
    }

    /**
     * Create an instance of {@link LineAmountsSimplifiedType }
     * 
     */
    public LineAmountsSimplifiedType createLineAmountsSimplifiedType() {
        return new LineAmountsSimplifiedType();
    }

    /**
     * Create an instance of {@link CostCentersType }
     * 
     */
    public CostCentersType createCostCentersType() {
        return new CostCentersType();
    }

    /**
     * Create an instance of {@link AdditionalDataType }
     * 
     */
    public AdditionalDataType createAdditionalDataType() {
        return new AdditionalDataType();
    }

    /**
     * Create an instance of {@link LineGrossAmountDataType }
     * 
     */
    public LineGrossAmountDataType createLineGrossAmountDataType() {
        return new LineGrossAmountDataType();
    }

    /**
     * Create an instance of {@link CustomerTaxNumberType }
     * 
     */
    public CustomerTaxNumberType createCustomerTaxNumberType() {
        return new CustomerTaxNumberType();
    }

}
