//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Clauses according to the Act LXXXV of 2011 on Environmental Protection Product Fee (related to the item)
 * 
 * <p>Java class for ProductFeeClauseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductFeeClauseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="productFeeTakeoverData" type="{http://schemas.nav.gov.hu/OSA/3.0/data}ProductFeeTakeoverDataType"/>
 *         &lt;element name="customerDeclaration" type="{http://schemas.nav.gov.hu/OSA/3.0/data}CustomerDeclarationType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductFeeClauseType", propOrder = {
    "productFeeTakeoverData",
    "customerDeclaration"
})
public class ProductFeeClauseType {

    protected ProductFeeTakeoverDataType productFeeTakeoverData;
    protected CustomerDeclarationType customerDeclaration;

    /**
     * Gets the value of the productFeeTakeoverData property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFeeTakeoverDataType }
     *     
     */
    public ProductFeeTakeoverDataType getProductFeeTakeoverData() {
        return productFeeTakeoverData;
    }

    /**
     * Sets the value of the productFeeTakeoverData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFeeTakeoverDataType }
     *     
     */
    public void setProductFeeTakeoverData(ProductFeeTakeoverDataType value) {
        this.productFeeTakeoverData = value;
    }

    /**
     * Gets the value of the customerDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDeclarationType }
     *     
     */
    public CustomerDeclarationType getCustomerDeclaration() {
        return customerDeclaration;
    }

    /**
     * Sets the value of the customerDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDeclarationType }
     *     
     */
    public void setCustomerDeclaration(CustomerDeclarationType value) {
        this.customerDeclaration = value;
    }

}
