//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Field type including the different product and service codes
 * 
 * <p>Java class for ProductCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductCodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productCodeCategory" type="{http://schemas.nav.gov.hu/OSA/3.0/data}ProductCodeCategoryType"/>
 *         &lt;choice>
 *           &lt;element name="productCodeValue" type="{http://schemas.nav.gov.hu/OSA/3.0/data}ProductCodeValueType"/>
 *           &lt;element name="productCodeOwnValue" type="{http://schemas.nav.gov.hu/NTCA/1.0/common}SimpleText255NotBlankType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductCodeType", propOrder = {
    "productCodeCategory",
    "productCodeValue",
    "productCodeOwnValue"
})
public class ProductCodeType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ProductCodeCategoryType productCodeCategory;
    protected String productCodeValue;
    protected String productCodeOwnValue;

    /**
     * Gets the value of the productCodeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCodeCategoryType }
     *     
     */
    public ProductCodeCategoryType getProductCodeCategory() {
        return productCodeCategory;
    }

    /**
     * Sets the value of the productCodeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCodeCategoryType }
     *     
     */
    public void setProductCodeCategory(ProductCodeCategoryType value) {
        this.productCodeCategory = value;
    }

    /**
     * Gets the value of the productCodeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCodeValue() {
        return productCodeValue;
    }

    /**
     * Sets the value of the productCodeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCodeValue(String value) {
        this.productCodeValue = value;
    }

    /**
     * Gets the value of the productCodeOwnValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCodeOwnValue() {
        return productCodeOwnValue;
    }

    /**
     * Sets the value of the productCodeOwnValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCodeOwnValue(String value) {
        this.productCodeOwnValue = value;
    }

}
