//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Gross data of the invoice summary
 * 
 * <p>Java class for SummaryGrossDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SummaryGrossDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="invoiceGrossAmount" type="{http://schemas.nav.gov.hu/OSA/3.0/base}MonetaryType"/>
 *         &lt;element name="invoiceGrossAmountHUF" type="{http://schemas.nav.gov.hu/OSA/3.0/base}MonetaryType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SummaryGrossDataType", propOrder = {
    "invoiceGrossAmount",
    "invoiceGrossAmountHUF"
})
public class SummaryGrossDataType {

    @XmlElement(required = true)
    protected BigDecimal invoiceGrossAmount;
    @XmlElement(required = true)
    protected BigDecimal invoiceGrossAmountHUF;

    /**
     * Gets the value of the invoiceGrossAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInvoiceGrossAmount() {
        return invoiceGrossAmount;
    }

    /**
     * Sets the value of the invoiceGrossAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInvoiceGrossAmount(BigDecimal value) {
        this.invoiceGrossAmount = value;
    }

    /**
     * Gets the value of the invoiceGrossAmountHUF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInvoiceGrossAmountHUF() {
        return invoiceGrossAmountHUF;
    }

    /**
     * Sets the value of the invoiceGrossAmountHUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInvoiceGrossAmountHUF(BigDecimal value) {
        this.invoiceGrossAmountHUF = value;
    }

}
