//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Data of calculation of invoice totals
 * 
 * <p>Java class for SummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="summaryNormal" type="{http://schemas.nav.gov.hu/OSA/3.0/data}SummaryNormalType"/>
 *           &lt;element name="summarySimplified" type="{http://schemas.nav.gov.hu/OSA/3.0/data}SummarySimplifiedType" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;element name="summaryGrossData" type="{http://schemas.nav.gov.hu/OSA/3.0/data}SummaryGrossDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SummaryType", propOrder = {
    "summaryNormal",
    "summarySimplified",
    "summaryGrossData"
})
public class SummaryType {

    protected SummaryNormalType summaryNormal;
    protected List<SummarySimplifiedType> summarySimplified;
    protected SummaryGrossDataType summaryGrossData;

    /**
     * Gets the value of the summaryNormal property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryNormalType }
     *     
     */
    public SummaryNormalType getSummaryNormal() {
        return summaryNormal;
    }

    /**
     * Sets the value of the summaryNormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryNormalType }
     *     
     */
    public void setSummaryNormal(SummaryNormalType value) {
        this.summaryNormal = value;
    }

    /**
     * Gets the value of the summarySimplified property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the summarySimplified property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSummarySimplified().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SummarySimplifiedType }
     * 
     * 
     */
    public List<SummarySimplifiedType> getSummarySimplified() {
        if (summarySimplified == null) {
            summarySimplified = new ArrayList<SummarySimplifiedType>();
        }
        return this.summarySimplified;
    }

    /**
     * Gets the value of the summaryGrossData property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryGrossDataType }
     *     
     */
    public SummaryGrossDataType getSummaryGrossData() {
        return summaryGrossData;
    }

    /**
     * Sets the value of the summaryGrossData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryGrossDataType }
     *     
     */
    public void setSummaryGrossData(SummaryGrossDataType value) {
        this.summaryGrossData = value;
    }

}
