//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:27 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitOfMeasureType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitOfMeasureType">
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType15">
 *     &lt;enumeration value="PIECE"/>
 *     &lt;enumeration value="KILOGRAM"/>
 *     &lt;enumeration value="TON"/>
 *     &lt;enumeration value="KWH"/>
 *     &lt;enumeration value="DAY"/>
 *     &lt;enumeration value="HOUR"/>
 *     &lt;enumeration value="MINUTE"/>
 *     &lt;enumeration value="MONTH"/>
 *     &lt;enumeration value="LITER"/>
 *     &lt;enumeration value="KILOMETER"/>
 *     &lt;enumeration value="CUBIC_METER"/>
 *     &lt;enumeration value="METER"/>
 *     &lt;enumeration value="LINEAR_METER"/>
 *     &lt;enumeration value="CARTON"/>
 *     &lt;enumeration value="PACK"/>
 *     &lt;enumeration value="OWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UnitOfMeasureType")
@XmlEnum
public enum UnitOfMeasureType {


    /**
     * Piece
     * 
     */
    PIECE,

    /**
     * Kilogram
     * 
     */
    KILOGRAM,

    /**
     * Metric ton
     * 
     */
    TON,

    /**
     * Kilowatt hour
     * 
     */
    KWH,

    /**
     * Day
     * 
     */
    DAY,

    /**
     * Hour
     * 
     */
    HOUR,

    /**
     * Minute
     * 
     */
    MINUTE,

    /**
     * Month
     * 
     */
    MONTH,

    /**
     * Liter
     * 
     */
    LITER,

    /**
     * Kilometer
     * 
     */
    KILOMETER,

    /**
     * Cubic meter
     * 
     */
    CUBIC_METER,

    /**
     * Meter
     * 
     */
    METER,

    /**
     * Linear meter
     * 
     */
    LINEAR_METER,

    /**
     * Carton
     * 
     */
    CARTON,

    /**
     * Pack
     * 
     */
    PACK,

    /**
     * Own unit of measure
     * 
     */
    OWN;

    public String value() {
        return name();
    }

    public static UnitOfMeasureType fromValue(String v) {
        return valueOf(v);
    }

}
