//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 03:22:41 PM CET 
//


package hu.gov.nav.schemas.osa._3_0.base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvoiceCategoryType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InvoiceCategoryType">
 *   &lt;restriction base="{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType15">
 *     &lt;enumeration value="NORMAL"/>
 *     &lt;enumeration value="SIMPLIFIED"/>
 *     &lt;enumeration value="AGGREGATE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InvoiceCategoryType")
@XmlEnum
public enum InvoiceCategoryType {


    /**
     * Normal (not simplified and not aggregate) invoice
     * 
     */
    NORMAL,

    /**
     * Simplified invoice
     * 
     */
    SIMPLIFIED,

    /**
     * Aggregate invoice
     * 
     */
    AGGREGATE;

    public String value() {
        return name();
    }

    public static InvoiceCategoryType fromValue(String v) {
        return valueOf(v);
    }

}
